### ISSUE TITLE
Error: Undefined index: vendorIds

### ISSUE THREAD

**Issue by Qraxin** [dynata/iab-tcf-php#1]
Hello, @NicolasBringas 

I get the error:

> _Undefined index: vendorIds_ at _vendor/dynata/iabtcf/src/TCFv2/Decoder.php:60_

for the following string:

> CPJmIgtPJmIgtAGABCDEBjCgAP_AAEPAAAYgHUhd5DrMTWFAUXxZQtsgGYgU1sQXAGQCCBCAAyABAAGA8AQAsUASEASAAAACAAAAowIBAAAEGAFEAAAAAAAEABAAAAQAgAAIIAJAAAEAAAIAAAgIAAAAAAAAAAAACAAAmAAQI-aABEAAAIAwQgAAAAAAAAAAAAIHBQEAAEAAXAA-AL4AhABFQC6gF6AMCAYoA8gB9gEIALaAaaA4IBIZAEACZAPsA_ACOALzEQBQBDAD8AQ2Ai8BIggACACQJAqAAQAAsACoAGQAOAAgABkADQAHkARABFACYAE8AN4AcwA_ACEAENAIgAiQBLACaAFKALcAYYA1YB9gH6ARoAjgBKQC5gGKANoAbgA9ACGwEXgJEAUOAvMBgwDDQGnANZCgAQBfBAAIAJA0AcALgAhgB-AIbAReAkQBjAqAMAEwALgA_ACOAJBAXmOgZgALAAqABkADgAIAAZAA0AB4AD6AIgAigBMACeAFwAL4AYgA3gBzAD8AIQAQ0AiACJAEsAJgATQApQBYgC3AGGANGAfYB-gEWAI4ASkAuYBeQDFAG0ANwAegBDYCLwEggJEAUOAvMBgwDDQGJAMYAZYA04eABAF8OAAgAkIQEgAFgAZACYAFwAL4AYgA3gCxgH2AfgBHACUgFzAMUAbQA9ACQQEiAMSIgAQBfEoDAACAAFgAZAA4ADwAIgATAAuABfADEAIQAQ0AiACJAFKALcAaoA_ACOAGKANwAi8BIgC8

UPD:
I created the pull request, please take a look: https://github.com/dynata/iab-tcf-php/pull/2

**Comment by NicolasBringas** [comment]
Hi @Qraxin,

Thank you for the contribution, added a changelog and updated a test case for this.

It's on the 1.0.1 release.
